baseURL = "https://softwareunicorns.com/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Software Unicorns"
theme = "LoveIt"

[params]
  version = "0.2.X"
  keywords = [
    "software development",
    "software consulting",
    "software engineering"
  ]
  images = ["/images/aaronqian.png"]

  [params.app]
    svgFavicon = ""

  [params.header]
    [params.header.title]
      logo = "/logo.svg"
      name = "Software Unicorns"

  [params.footer]
    enable = true
    custom = ''
    hugo = false
    copyright = true
    author = true
    since = 2021
    license= '<a rel="license external nofollow noopener noreffer" href="https://opensource.org/licenses/MIT" target="_blank">MIT License</a>'

  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      avatarURL = "/images/aaronqian.png"
      title = "Hi, I'm Aaron Qian"
      subtitle = "I Solve Difficult Software Problems"
      typeit = true
      social = true

  [params.social]
    GitHub = "aq1018"
    Linkedin = "aaronqian"
    Twitter = "aq1018"
    Facebook = "aaron.qian.9"
    Stackoverflow = "86288"
    Email = "aaron@bubabutech.com"
    RSS = true

  [params.section]
    paginate = 10
    dateFormat = "01/02"
    rss = 10

  [params.list]
    paginate = 10
    dateFormat = "01/02"
    rss = 10

  [params.page]
    [params.page.code]
      maxShownLines = 500

    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true

    [params.page.comment]
      enable = true
      [params.page.comment.disqus]
        enable = true
        shortname = "softwareunicorns"

  [params.analytics]
    enable = true
    [params.analytics.google]
      id = "G-CR6HY18MJR"
      anonymizeIP = true

[author]
  name = "Aaron Qian"
  email = "aaron@bubabutech.com"
  link = "/about/"

[menu]
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 4

[markup]
  [markup.highlight]
    noClasses = false
