baseURL = "https://softwareunicorns.com/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Software Unicorns"
theme = "LoveIt"

[params]
  version = "0.2.X"
  keywords = [
    "software development",
    "software consulting",
    "software engineering"
  ]
  images = ["/images/aaronqian.png"]

  [params.app]
    svgFavicon = ""

  [params.header]
    [params.header.title]
      pre = '<span style="display:inline-block;width: 2rem;height: 2rem"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><path fill=currentColor d="M631.98 32H531.73c5.93-6.14 10.4-13.63 12.18-22.36 1.01-4.96-2.88-9.64-7.94-9.64H416c-70.69 0-128 57.31-128 128H160c-28.84 0-54.4 12.98-72 33.11V160c-48.53 0-88 39.47-88 88v56c0 8.84 7.16 16 16 16h16c8.84 0 16-7.16 16-16v-56c0-13.22 6.87-24.39 16.78-31.68-.21 2.58-.78 5.05-.78 7.68 0 27.64 11.84 52.36 30.54 69.88l-25.72 68.6a63.945 63.945 0 0 0-2.16 37.99l24.85 99.41A15.982 15.982 0 0 0 107.02 512h65.96c10.41 0 18.05-9.78 15.52-19.88l-26.31-105.26 23.84-63.59 102.04 22.33V496c0 8.84 7.16 16 16 16h64c8.84 0 16-7.16 16-16V318.22c19.74-20.19 32-47.75 32-78.22 0-.22-.07-.42-.08-.64V136.89l16 7.11 18.9 37.7c7.45 14.87 25.05 21.55 40.49 15.37l32.55-13.02a31.997 31.997 0 0 0 20.12-29.74L544 83.3l92.42-36.65c6.59-4.38 3.48-14.65-4.44-14.65zM480 96c-8.84 0-16-7.16-16-16s7.16-16 16-16 16 7.16 16 16-7.16 16-16 16z"/></svg></span>'
      name = "Software Unicorns"

  [params.footer]
    enable = true
    custom = ''
    hugo = false
    copyright = true
    author = true
    since = 2021
    license= '<a rel="license external nofollow noopener noreffer" href="https://opensource.org/licenses/MIT" target="_blank">MIT License</a>'

  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      avatarURL = "/images/aaronqian.png"
      title = "Hi, I'm Aaron Qian"
      subtitle = "I Solve Difficult Software Problems"
      typeit = true
      social = true

  [params.social]
    GitHub = "aq1018"
    Linkedin = "aaronqian"
    Twitter = "aq1018"
    Facebook = "aaron.qian.9"
    Stackoverflow = "86288"
    Email = "aaron@bubabutech.com"
    RSS = true

  [params.section]
    paginate = 10
    dateFormat = "01/02"
    rss = 10

  [params.list]
    paginate = 10
    dateFormat = "01/02"
    rss = 10

  [params.page]
    [params.page.code]
      maxShownLines = 500

    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true

    [params.page.comment]
      enable = true
      [params.page.comment.disqus]
        enable = true
        shortname = "softwareunicorns"

  [params.analytics]
    enable = true
    [params.analytics.google]
      id = "G-CR6HY18MJR"
      anonymizeIP = true

[author]
  name = "Aaron Qian"
  email = "aaron@bubabutech.com"
  link = "/about/"

[menu]
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 4

[markup]
  [markup.highlight]
    noClasses = false
