base_url = "https://softwareunicorns.com"
theme = "DeepThought"
taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

[languages.en]
compile_sass = true
build_search_index = false
title = "Software Unicorns"


[markdown]
highlight_code = true

[extra]
navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/about", name = "About" },
  { url = "$BASE_URL/daily-tips", name = "Daily Tips" },
 ]},
]

toggle_dark_theme = false

# Add links to favicon, you can use https://realfavicongenerator.net/ to generate favicon for your site
[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = "Aaron Qian"
avatar = "/images/aaronqian.png"

# Social links
[extra.social]
email = "aaron@bubabutech.com"
facebook = "aaron.qian.9"
github = "aq1018"
# gitlab = "<gitlab_username>"
# keybase = "<keybase_username>"
linkedin = "aaronqian"
stackoverflow = "86288"
twitter = "aq1018"
# instagram = "<instagram_usernaem>"
# behance = "<behance_username>"
# google_scholar = "<googlescholar_userid>"
# orcid = "<orcid_userid>"


# To add google analytics
[extra.analytics]
google = "G-CR6HY18MJR"

# To add disqus comments
[extra.commenting]
disqus = "<your_disqus_shortname>"

# To enable mapbox maps
[extra.mapbox]
access_token = "<your_access_token>"
